receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    timeout: 5s
  resource/add:
    attributes:
      - key: service.name
        action: upsert
        value: "student"

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

  # prometheus:
  #   endpoint: "0.0.0.0:9090"
  #   resource_to_telemetry_conversion:
  #     enabled: true
  

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource/add]
      exporters: [prometheusremotewrite]
